spring:
  datasource:
    url: jdbc:postgresql://db:5432/dservice?currentSchema=service
    username: postgres
    password: 1769
  rabbitmq:
    host: rabbitmq
    port: 5672
  data:
    redis:
      host: redis
      port: 6379