spring:
  datasource:
    url: jdbc:postgresql://db:5432/dservice?currentSchema=service
    username: postgres
    password: 1769
  kafka:
    bootstrap-servers:
      - kafka:9092
    consumer:
      group-id: dservice
  data:
    redis:
      host: redis
      port: 6379