spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dservice?currentSchema=service
    username: postgres
    password: 1769
  kafka:
    bootstrap-servers: 
    - localhost:9092
    consumer:
      group-id: dservice
  data:
    redis:
      host: localhost
      port: 6379